name: ClashElixir

options:
  bundleIdPrefix: com.monprojet
  deploymentTarget:
    iOS: "16.0"
  createIntermediateGroups: true

targets:

  ClashElixir:
    type: application
    platform: iOS
    sources:
      - path: App
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.monprojet.clashelixir
        PRODUCT_NAME: ClashElixir
        MARKETING_VERSION: "1.0"
        CURRENT_PROJECT_VERSION: "1"
        INFOPLIST_FILE: App/Info.plist
        GENERATE_INFOPLIST_FILE: NO
        SWIFT_VERSION: "5.0"
        TARGETED_DEVICE_FAMILY: "1"
    dependencies:
      - target: BroadcastExt
        embed: true

  BroadcastExt:
    type: app-extension
    platform: iOS
    sources:
      - path: Broadcast
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.monprojet.clashelixir.broadcast
        PRODUCT_NAME: BroadcastExt
        MARKETING_VERSION: "1.0"
        CURRENT_PROJECT_VERSION: "1"
        INFOPLIST_FILE: Broadcast/Info.plist
        GENERATE_INFOPLIST_FILE: NO
        SWIFT_VERSION: "5.0"
        TARGETED_DEVICE_FAMILY: "1"
